# Allgemeine Einstellungen
server:
  host: "0.0.0.0"
  port: 8000

# KI-Modelle
models:
  text_model: "local-german-model"  # Name deines Textmodells
  speech_model: "piper"             # F체r Sprachsynthese
  speech_recognition: "whisper"     # F체r Spracheingabe

# Websuche aktivieren/deaktivieren
web_search:
  enabled: true
  max_results: 5

# Dokumentenverarbeitung
docs:
  folder: "./docs"
  index_file: "./memory/docs_index.faiss"

# Ged채chtnis
memory:
  folder: "./memory"
  max_entries_per_user: 1000

# Benutzerverwaltung
users_file: "./users.json"

# UI
ui:
  dark_mode_auto: true      # Passt Dark/Light automatisch an OS an
  mobile_optimized: true    # Optimiert UI f체r Handy/Tablet
